"use client";

import { useEffect, useRef, useState } from "react";
import type { PlacementMask } from "@/features/try-on/types";

const proposal = (): PlacementMask => ({ width: 1, height: 1, points: [{ x: .2, y: .2 }, { x: .8, y: .2 }, { x: .8, y: .75 }, { x: .2, y: .75 }] });

export default function MaskStep({ previewUrl, mask, onChange, onConfirm, onBack, error }: { previewUrl: string; mask: PlacementMask | null; onChange: (mask: PlacementMask) => void; onConfirm: () => void; onBack: () => void; error: string | null }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [editing, setEditing] = useState(false); const current = mask ?? proposal(); const [drag, setDrag] = useState<number | null>(null);
  useEffect(() => { if (mask === null) onChange(proposal()); }, [mask, onChange]);
  useEffect(() => { const c = canvas.current; if (!c) return; const context = c.getContext("2d"); if (!context) return; const image = new Image(); image.onload = () => { c.width = image.naturalWidth || 800; c.height = image.naturalHeight || 600; context.drawImage(image, 0, 0, c.width, c.height); context.fillStyle = "rgba(59,130,246,.25)"; context.strokeStyle = "#2563eb"; context.lineWidth = Math.max(3, c.width / 250); context.beginPath(); current.points.forEach((point, i) => i ? context.lineTo(point.x * c.width, point.y * c.height) : context.moveTo(point.x * c.width, point.y * c.height)); context.closePath(); context.fill(); context.stroke(); current.points.forEach((point) => { context.beginPath(); context.fillStyle = "white"; context.arc(point.x * c.width, point.y * c.height, Math.max(8, c.width / 80), 0, Math.PI * 2); context.fill(); context.stroke(); }); }; image.src = previewUrl; }, [previewUrl, current]);
  const updateFromPointer = (event: React.PointerEvent<HTMLCanvasElement>) => { if (drag === null) return; const rect = event.currentTarget.getBoundingClientRect(); const x = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); const y = Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)); onChange({ ...current, points: current.points.map((point, index) => index === drag ? { x, y } : point) }); };
  const nearest = (event: React.PointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width; const y = (event.clientY - rect.top) / rect.height; return current.points.reduce((best, point, index) => Math.hypot(point.x - x, point.y - y) < Math.hypot(current.points[best].x - x, current.points[best].y - y) ? index : best, 0); };
  return <section className="mx-auto w-full max-w-2xl px-4 py-8"><p className="text-sm font-medium text-primary">Шаг 3 из 3</p><h1 className="mt-2 text-3xl font-bold">Область размещения</h1><p className="mt-3 text-sm text-muted-foreground">Это редактируемое предложение, а не автоматическое определение зоны.</p><div className="relative mt-5 overflow-hidden rounded-xl border"><canvas ref={canvas} className="block h-auto w-full touch-none" aria-label="Редактируемая область размещения на фото" onPointerDown={(e) => { if (editing) { e.currentTarget.setPointerCapture(e.pointerId); setDrag(nearest(e)); } }} onPointerMove={updateFromPointer} onPointerUp={() => setDrag(null)} /></div><div className="mt-4 flex flex-wrap gap-3"><button type="button" className="min-h-11 rounded-lg border px-4" onClick={() => setEditing(!editing)}>{editing ? "Готово" : "Изменить область"}</button><button type="button" className="min-h-11 rounded-lg border px-4" onClick={() => onChange(proposal())}>Сбросить предложение</button></div><fieldset className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><legend className="mb-2 text-sm font-medium">Точные координаты углов, %</legend>{current.points.flatMap((point, index) => (["x", "y"] as const).map((axis) => <label key={`${axis}${index}`} className="text-xs">{axis}{index + 1}<input aria-label={`${axis.toUpperCase()} ${index + 1}, процент`} className="mt-1 min-h-11 w-full rounded border px-2 text-sm" type="number" min="0" max="100" value={Math.round(point[axis] * 100)} onChange={(e) => { const value = Math.max(0, Math.min(100, Number(e.target.value) || 0)) / 100; onChange({ ...current, points: current.points.map((p, i) => i === index ? { ...p, [axis]: value } : p) }); }} /></label>))}</fieldset>{error && <p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}<div className="mt-6 flex flex-wrap gap-3"><button className="min-h-11 rounded-lg border px-4" type="button" onClick={onBack}>Назад</button><button className="min-h-11 rounded-lg bg-primary px-4 text-primary-foreground" type="button" onClick={onConfirm}>Подтвердить и создать примерку</button></div></section>;
}
